version: 0.1.1                                            

name: Deploy a Next.js site to Digital Ocean Apps     
description: A stack to deploy a nextjs based website to Digital Ocean Apps              

branding:                                                # stack branding 
 icon: 'package'
 color: 'black'

inputs:                                                  # stack inputs 
  - name: NODE_VERSION                                   # stack input name
    default: v12.22.4                                    # stack input default value provided
    description: NODE_VERSION for nodejs stack           # stack input description
    validvalues:                                         # stack input valid values that can be selected
    - v12.22.4
    - v14.17.4
    
  - name: DIGITAL_OCEAN_ACCESS_TOKEN
    description: Enter the DigitalOcean Access Token. 
    is-secret: true
    required: true
    
  - name: CURRENT_REPOSITORY
    description: Enter the current repository name. 
    is-secret: true
    required: true
    

configs:
  repo-metadata:
    parameters:
      description: 'NextJS app on Digital Ocean Apps'
      secrets: 
      - name: DIGITAL_OCEAN_ACCESS_TOKEN
        value: ${{inputs.DIGITAL_OCEAN_ACCESS_TOKEN}}
      - name: CURRENT_REPO
        value: ${{inputs.CURRENT_REPOSITORY}}
      topics:
      - nextjs
      - github-pages

  environments:
    - name: development
      parameters:
        protected-branches: false
        allowed-branch-rules:
          - main
          - releases/*

init:
  uses: "stack-init.yaml"
