alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
name: nextjs-do-workflow-test
region: blr
services:
- build_command: npm run build
  environment_slug: node-js
  github:
    branch: main
    repo: <CURRENT_REPOSITORY_NAME>
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  name: nextjs-digital-ocean-stack
  routes:
  - path: /
  run_command: npm start
  source_dir: /
