name: "build"

on: [push]

jobs:
  vercel: 
    runs-on: ubuntu-latest
    name: "build nextjs app"
    
    
    steps:
       - name: checkout
         uses: actions/checkout@v2
         with:
           persist-credentials: false
           
       - name: Display file
         run: |
            echo ${GITHUB_REPOSITORY}
            echo ${{ env.GITHUB_REPOSITORY }}
            cat ${GITHUB_WORKSPACE}/config/spec.yaml
            
       - name: Replace Action
         uses: datamonsters/replace-action@v2
         with:
            files: 'config/spec.yaml'
            replacements: '<CURRENT_REPOSITORY_NAME>=$REPO'

            
