name: "build"

on: [push]

jobs:
  vercel: 
    runs-on: ubuntu-latest
    name: "build nextjs app"
    
    
    steps:
       - name: checkout
         uses: actions/checkout@v2
         with:
           persist-credentials: false
           
       - name: Display file
         run: |
            echo ${GITHUB_WORKSPACE}
            pwd
            cat ${GITHUB_WORKSPACE}/config/spec.yaml
            sed -i "s/<CURRENT_REPOSITORY_NAME>/${GITHUB_REPOSITORY}/g" ${GITHUB_WORKSPACE}/config/spec.yaml
            cat config/spec.yaml
            
