on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'

jobs:

  build:
    name: Build, push, and deploy
    runs-on: ubuntu-latest
    steps:
    - name: use node.js 
      uses: actions/checkout@v2
      with:
        node-version-file: '.nvmrc'
        registry-url: https://registry.npmjs.org/
        
    - name:  use node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
          node-version-file: '.nvmrc'
          registry-url: https://registry.npmjs.org/
          
    - name: install dependencies
      run: npm install
      
    - name: run build
      run: npm run build

    - name: run tests
      run: npm test
      env:
        CI: true
        FORCE_COLOR: 1

    - name: Update SHA
      run: echo $GITHUB_SHA > $GITHUB_WORKSPACE/site/_meta

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Deploy to DigitalOcean Kubernetes
      run: doctl apps create --spec $GITHUB_WORKSPACE/config/spec.yml --wait 
