on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'

jobs:

  build:
    name: Build, push, and deploy
    runs-on: ubuntu-latest
    steps:
    - name: use node.js 
      uses: actions/checkout@v2
      with:
        node-version-file: '.nvmrc'
        registry-url: https://registry.npmjs.org/

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    
    - name: shell commands
      run: |
         echo $GITHUB_WORKSPACE
         cd $GITHUB_WORKSPACE
         pwd
         ls -ltr
         cd config
         ls -ltr
      

    - name: Deploy to DigitalOcean Kubernetes
      run: doctl apps create --spec  $GITHUB_WORKSPACE/config/spec.yaml --wait 
